function keyRelease(~, event)
% Key release function, generated by ChatGPT
    global keys;
    if isfield(keys, event.Key)
        keys.(event.Key) = false; % Set key state to "released"
    end
end